name: Deploy ASP.NET Core App to Azure App Service

on:
  push:
    branches:
      - main # Ensure this matches your main branch name
  workflow_dispatch: # Allows manual triggering of the workflow

env:
  AZURE_WEBAPP_NAME: lostandfound # Replace with your App Service name
  # IMPORTANT: Replace 'ProjectBB' below with the actual folder name
  # where your .csproj or .sln file is located within your repository.
  PROJECT_SOURCE_PATH: './ProjectBB' # <--- ADDED/MODIFIED: Path to your main project folder
  AZURE_WEBAPP_PACKAGE_PATH: '.' # Adjust if your build output is in a subfolder, e.g., './publish'
  DOTNET_VERSION: '8.x' # Ensure this matches your project's target .NET version
  EF_CORE_VERSION: '8.0.*' # Ensure this matches your Entity Framework Core NuGet package version

jobs:
  build-and-deploy:
    runs-on: windows-latest # Using Windows agent as it's an ASP.NET Core app

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET Core SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
      run: dotnet restore
      working-directory: ${{ env.PROJECT_SOURCE_PATH }} # <--- ADDED: Execute from project directory

    - name: Build the application
      run: dotnet build --configuration Release --no-restore
      working-directory: ${{ env.PROJECT_SOURCE_PATH }} # <--- ADDED: Execute from project directory

    - name: Publish the application
      # Publishes the application to a 'publish' folder at the root of the workspace
      run: dotnet publish --configuration Release --no-build --output ${{ github.workspace }}/publish
      working-directory: ${{ env.PROJECT_SOURCE_PATH }} # <--- ADDED: Execute from project directory

    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v3
      with:
        app-name: ${{ env.AZURE_WEBAPP_NAME }}
        slot-name: 'Production' # Or your specific deployment slot
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }} # Ensure this secret is set in GitHub
        package: ${{ github.workspace }}/publish # Package path from the publish step

    # --- Database Migrations (Crucial for Schema Updates) ---
    # This section ensures your Azure SQL Database schema is up-to-date
    # after your application is deployed.
    - name: Install dotnet-ef global tool
      # Install dotnet-ef global tool into the runner's environment
      # The --version should match your Entity Framework Core NuGet package version
      run: dotnet tool install --global dotnet-ef --version ${{ env.EF_CORE_VERSION }}

    - name: Add dotnet-ef to PATH for current session
      # Explicitly add the tools directory to PATH for the current job session
      # This addresses the "command not recognized" issue in PowerShell on Azure runners
      run: |
        $env:PATH = $env:PATH + ";C:\Users\runneradmin\.dotnet\tools" # Default path for global tools on windows-latest runner
      shell: powershell # Specify PowerShell shell for this command

    - name: Run EF Core Database Migrations
      # Execute database migrations against your Azure SQL Database
      # --project and --startup-project point to your main project file (e.g., 'ProjectBB.csproj')
      # The working-directory MUST be where your .csproj file resides for EF Core to find it.
      run: dotnet-ef database update --project "ProjectBB.csproj" --startup-project "ProjectBB.csproj" # <--- ADJUSTED: Use your actual project file name
      working-directory: ${{ env.PROJECT_SOURCE_PATH }} # <--- ADDED/MODIFIED: Run EF migrations from source project path
      env:
        # ASPNETCORE_ENVIRONMENT is typically set in Azure App Service config,
        # but can be set here if needed for migration-specific logic
        ASPNETCORE_ENVIRONMENT: Production
